# Generated by Django 5.2.1 on 2025-07-02 01:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('contenu', models.TextField()),
                ('destinataire', models.IntegerField(blank=True, help_text='ID du collaborateur provenant du service externe', null=True)),
                ('destinateur', models.IntegerField(blank=True, help_text='ID du collaborateur provenant du service externe', null=True)),
                ('tache', models.CharField(blank=True, help_text='ID de la tache provenant du service externe', null=True)),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
    ]
