# Generated by Django 5.2.1 on 2025-07-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='destinataire',
            field=models.IntegerField(blank=True, help_text='ID du collaborateur provenant du service de gestion des collaborateurs', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='destinateur',
            field=models.IntegerField(blank=True, help_text='ID du collaborateur provenant du service de gestion des collaborateurs', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tache',
            field=models.IntegerField(blank=True, help_text='ID de la tache provenant du service de gestion des taches', null=True),
        ),
    ]
