# Generated by Django 5.2.1 on 2025-07-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_alter_notification_destinataire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='destinateur',
            field=models.EmailField(default='collabtask86@gmail.com', max_length=254),
        ),
    ]
